#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum planck_layers {
  _MAIN,
  _RAISE,
  _LOWER,
  _SETTINGS,
  _ADJUST
};

enum custom_keycodes {
  WINDOW_MNGR = SAFE_RANGE,
  SPLIT_LE,
  SPLIT_RI,
  TOP_LE,
  TOP_RI,
  BOT_LE,
  BOT_RI,
  NEXT_SCREEN,
  PREV_SCREEN,
  FULL_SCREEN,
  EDIT_ALL
};

#define LOWER MO(_LOWER)
#define RAISE MO(_RAISE)

layer_state_t layer_state_set_user(layer_state_t state) {
  return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
}

bool process_record_user(uint16_t keycode, keyrecord_t *record){
	switch(keycode){
    case(SPLIT_LE):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_LEFT)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(SPLIT_RI):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_RIGHT)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(TOP_LE):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_U)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(BOT_LE):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_J)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(TOP_RI):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_I)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(BOT_RI):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_K)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(NEXT_SCREEN):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_DOWN(X_LGUI)SS_TAP(X_RIGHT)SS_UP(X_LGUI)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(PREV_SCREEN):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_DOWN(X_LGUI)SS_TAP(X_LEFT)SS_UP(X_LGUI)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(FULL_SCREEN):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LCTRL)SS_DOWN(X_LALT)SS_TAP(X_ENTER)SS_UP(X_LALT)SS_UP(X_LCTRL));
        return false;
      }
      break;
    case(EDIT_ALL):
      if(record->event.pressed){
        send_string(SS_DOWN(X_LGUI)SS_TAP(X_F2)SS_UP(X_LGUI));
        return false;
      }
      break;
    }

	return true;
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  /* MAIN
  * ,-----------------------------------------------------------------------------------.
  * | Tab  |   Q  |   W  |   E  |   R  |   T  |   Y  |   U  |   I  |   O  |   P  | Bksp |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * | Esc  |   A  |   S  |   D  |   F  |   G  |   H  |   J  |   K  |   L  |   ;  |  "   |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * | Shift|   Z  |   X  |   C  |   V  |   B  |   N  |   M  |   ,  |   .  |   /  |Enter |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * | Brite| Ctrl | Alt  | GUI  |Lower |    Space    |Raise | Left | Down |  Up  |Right |
  * `-----------------------------------------------------------------------------------'
  */
	[_MAIN] = LAYOUT_planck_1x2uC(	
    KC_TAB,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_BSPC,
    KC_GESC,  KC_A,     KC_S,     KC_D,     KC_F,     KC_G,     KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN,  KC_QUOT,
    KC_LSFT,  KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_N,     KC_M,     KC_COMM,  KC_DOT,   KC_SLSH,  KC_ENT,
    TT(3),    KC_LCTL,  KC_LALT,  KC_LGUI,  LOWER,         KC_SPC,        RAISE,   KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT
  ),


	[_RAISE] = LAYOUT_planck_1x2uC(	
    KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_CIRC,  KC_AMPR,  KC_ASTR,  KC_LPRN,  KC_RPRN,  KC_MINS,  KC_EQL,
    KC_GRV,   KC_NO,    KC_NO,    KC_LBRC,  KC_RBRC,  KC_NO,    KC_NO,    KC_MINS,  KC_PLUS,  KC_LCBR,  KC_RCBR,  KC_BSLS,
    KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,       KC_SPC,        KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS
  ),


	[_LOWER] = LAYOUT_planck_1x2uC(
    KC_TRNS,  KC_NO,    KC_UP,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS,  KC_CIRC,  KC_7,     KC_8,     KC_9,     KC_TRNS,
    TO(0),    KC_LEFT,  KC_DOWN,  KC_RGHT,  KC_NO,    KC_NO,    KC_NO,    KC_PEQL,  KC_4,     KC_5,     KC_6,     KC_PAST,
    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_1,     KC_2,     KC_3,     KC_PMNS,
    KC_NO,    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,       KC_TRNS,       KC_NO,    KC_0,     KC_DOT,   KC_PSLS,  KC_PPLS
  ),


	[_SETTINGS] = LAYOUT_planck_1x2uC(
    KC_NO,    RESET,    DEBUG,    KC_NO,    KC_NO,    KC_NO,    KC_BRID,  KC_BRIU,  KC_MUTE,  KC_VOLD,  KC_VOLU,  KC_NO,
    TO(0),    BL_INC,   BL_ON,    RGB_HUI,  RGB_VAI,  TOP_LE,   TOP_RI,   KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,
    KC_NO,    BL_DEC,   BL_OFF,   RGB_HUD,  RGB_VAD,  BOT_LE,   BOT_RI,   KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,
    KC_TRNS,  BL_TOGG,  BL_STEP,  BL_BRTG,  SPLIT_LE,      FULL_SCREEN,   SPLIT_RI, KC_NO,    KC_NO,    KC_NO,    KC_NO
  ),

  /* ADJUST
  * ,-----------------------------------------------------------------------------------.
  * |   ~  | EDIT |   @  |   #  |   $  |   %  |   ^  |   &  |   *  |   (  |   )  | Bksp |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * | Del  |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |   _  |   +  |   {  |   }  |  |   |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * |      |  F7  |  F8  |  F9  |  F10 |  F11 |  F12 |ISO ~ |ISO | | Home | End  |      |
  * |------+------+------+------+------+------+------+------+------+------+------+------|
  * |      |      |      |      |      |             |      | Next | Vol- | Vol+ | Play |
  * `-----------------------------------------------------------------------------------'
  */
  [_ADJUST] = LAYOUT_planck_1x2uC(
    KC_TILD,  EDIT_ALL, KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_CIRC,  KC_AMPR,    KC_ASTR,    KC_LPRN, KC_RPRN, KC_BSPC,
    KC_DEL,   KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,    KC_UNDS,    KC_PLUS,    KC_LCBR, KC_RCBR, KC_PIPE,
    _______,  KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,   KC_F12,   S(KC_NUHS), S(KC_NUBS), KC_HOME, KC_END,  _______,
    _______,  _______,  _______,  _______,  _______,           _______,   _______,    KC_MNXT,    KC_VOLD, KC_VOLU, KC_MPLY
  )
};
